### PR TITLE
Replace Kite implementation to meet PDP-2 requirememnts

### PR DESCRIPTION
**Pull request by stephanesan**
Replace Kite implementation to meet PDP-2 requirememnts.

### CODE REVIEW

**Comment by jeclarke** [comment]
Could you squash this into a single commit?

**Comment by stephanesan** [comment]
This separation here was intentional and the reason for it is to clearly distinguish the original implementation (imported from gobblin) from the modifications needed to meet PNDA's needs.
Keeping those commits separate will ease importing evolutions of the original implementations into PNDA as we gobblin's version increments over time and this file evolves consequently.
Does this seem like an acceptable exception?

**Comment by jeclarke** [comment]
I see... just following the contrib guidelines :-), next one, could the PR have a better title?

**Comment by jeclarke** [comment]
Spelling mistake on "requirememnts", also while you're amending the commit msg don't end the comment title with a '.'

**Comment by stephanesan** [comment]
Altered the commit message to address the comments above.

**Pull request merged**
